name: mini-doodle
services:
  backend:
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE_NAME: ${PG_DATABASE_NAME}
      PG_HOST: ${PG_HOST}
    depends_on:
      - database
    build:
      context: ..
      dockerfile: .docker/Dockerfile.bk
    ports:
      - "8080:8080"

  database:
    image: postgres:16.3
    container_name: doodle_pg
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DATABASE_NAME}
    volumes:
      - pg_volumes:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433

volumes:
  pg_volumes:
